### ISSUE TITLE
Bizy

### ISSUE THREAD

**Issue by darkobizjak** [jeroenvermeulen/JeVe_EasyOTA#2]
Im asking for help. I am new in this field. I am connecting to the route and I have a wifi port. when I try to download the program via wifi I get this error message.

Arduino: 1.8.5 (Windows 7), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, 115200, 4M (3M SPIFFS)"

In file included from C:\Users\Darko\Documents\Arduino\Prehodi_barv\smrekca_iskrice_mavrica_svetlo_temno_prehodi_barve_in_barve23_W\smrekca_iskrice_mavrica_svetlo_temno_prehodi_barve_in_barve23_W.ino:2:0:

C:\Users\Darko\Documents\Arduino\libraries\FastLED/FastLED.h:17:21: note: #pragma message: FastLED version 3.001.006

 #    pragma message "FastLED version 3.001.006"

                     ^

In file included from C:\Users\Darko\Documents\Arduino\libraries\FastLED/FastLED.h:68:0,

                 from C:\Users\Darko\Documents\Arduino\Prehodi_barv\smrekca_iskrice_mavrica_svetlo_temno_prehodi_barve_in_barve23_W\smrekca_iskrice_mavrica_svetlo_temno_prehodi_barve_in_barve23_W.ino:2:

C:\Users\Darko\Documents\Arduino\libraries\FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

Archiving built core (caching) in: C:\Users\Darko\AppData\Local\Temp\arduino_cache_212063\core\core_esp8266_esp8266_nodemcu_CpuFrequency_80,UploadSpeed_115200,FlashSize_4M3M_2072eb5502d2d04e0c35978e1348c1c2.a
Sketch uses 259619 bytes (24%) of program storage space. Maximum is 1044464 bytes.
Global variables use 34136 bytes (41%) of dynamic memory, leaving 47784 bytes for local variables. Maximum is 81920 bytes.
java.io.IOException: Cannot run program "python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:26)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.GenericNetworkUploader.uploadUsingPreferences(GenericNetworkUploader.java:99)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
	at processing.app.SketchController.upload(SketchController.java:713)
	at processing.app.SketchController.exportApplet(SketchController.java:686)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2168)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
An error occurred while uploading the sketch

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by jeroenvermeulen** [comment]
Hi @darkobizjak, I don't think this error is caused by my `JeVe_EasyOTA` library.
There seems to be an error in your development setup on your Windows machine.
You seem to be missing "python.exe". I don't have a quick a solution, since I am developing on a Mac.
